### ISSUE TITLE
fwinfo reports 'UNKNOWN_METHOD'

### ISSUE THREAD

**Issue by BertLindeman** [sanjayseshan/spikeprime-tools#1]
Running Spike Prime hub with:
`MicroPython v1.12-1031-g542bff829 on 2020-08-11; LEGO Technic Large Hub with STM32F413xx`

Maybe due to recent firmware updates the `get_firmware_info` function is no longer available, or got another name.

```
 ./spikejsonrpcapispike.py fwinfo
Traceback (most recent call last):
  File "./spikejsonrpcapispike.py", line 205, in <module>
    args.func()
  File "./spikejsonrpcapispike.py", line 124, in handle_fwinfo
    info = rpc.get_firmware_info()
  File "./spikejsonrpcapispike.py", line 108, in get_firmware_info
    return self.send_message('get_firmware_info')
  File "./spikejsonrpcapispike.py", line 54, in send_message
    return self.recv_response(id)
  File "./spikejsonrpcapispike.py", line 63, in recv_response
    raise ConnectionError(error)
ConnectionError: {'message': 'get_firmware_info', 'type': 'UNKNOWN_METHOD'}
```

and
```
 ./spikejsonrpc.py fwinfo
Traceback (most recent call last):
  File "./spikejsonrpc.py", line 205, in <module>
    args.func()
  File "./spikejsonrpc.py", line 124, in handle_fwinfo
    info = rpc.get_firmware_info()
  File "./spikejsonrpc.py", line 108, in get_firmware_info
    return self.send_message('get_firmware_info')
  File "./spikejsonrpc.py", line 54, in send_message
    return self.recv_response(id)
  File "./spikejsonrpc.py", line 63, in recv_response
    raise ConnectionError(error)
ConnectionError: {'message': 'get_firmware_info', 'type': 'UNKNOWN_METHOD'}
```

I do not know how to look for the available functions, nor where to look for them.

Related and maybe helpful:
Connected the new Mindstorms Robot Inventor hub (set 51515) via USB.
Results in a different error:
```
./spikejsonrpc.py --debug fwinfo
DEBUG:root:sending: {"m": "get_firmware_info", "p": {}, "i": "4q6J"}
DEBUG:root:response: {'m': 'get_firmware_info', 'p': {}, 'i': '4q6J'}
Traceback (most recent call last):
  File "./spikejsonrpc.py", line 205, in <module>
    args.func()
  File "./spikejsonrpc.py", line 124, in handle_fwinfo
    info = rpc.get_firmware_info()
  File "./spikejsonrpc.py", line 108, in get_firmware_info
    return self.send_message('get_firmware_info')
  File "./spikejsonrpc.py", line 54, in send_message
    return self.recv_response(id)
  File "./spikejsonrpc.py", line 64, in recv_response
    return m['r']
KeyError: 'r'
```

**Comment by sanjayseshan** [comment]
That might be the problem. I will take a look when I get a chance. Do the other functions work? You probably should use ./spikejsonrpcapispike.py for both products (the spikejsonrpcapi.py seems to be incompatible with newer versions of the firmware and new spike/mindstorms API).

**Comment by BertLindeman** [comment]
Thank you for the fast response.
Another firmware came over today.
Still got the same error.
I will take a look at ./spikejsonrpcapispike.py

Bert

**Comment by BertLindeman** [comment]
Ah, I did not test many functions, but the list (ls) function does work.

I have made some changes (in another script) so the decoded name and some other fields are shown.
Nothing rocket science.
Sample output at the moment:

```
 # Name                                     Decoded Name                               Size     Id Last Modified        Project_id           Type
 0 YXZhaWxhYmxlbW9kdWxlcw==                 availablemodules                           740b  41475 2020-10-28 21:54:08  EePEg27-WCsk         python
 1 dHJ5X21vZHVsZXM=                         try_modules                                357b  51754 2020-09-18 10:39:11  JZGKRQp5EUqj         python
 3 ZGlyZWN0b3J5X2xpc3Q=                     directory_list                            1725b  11624 2020-07-27 19:54:17  AIKWkHYSy_Z9         python
 9 UHJpbWVDdWJlci12MXAx                     PrimeCuber-v1p1                           1662b  31645 2020-07-26 18:02:38  3z6tt5wxuY6u         python
10 YXZhaWxhYmxlbW9kdWxlcw==                 availablemodules                           494b  41154 2020-07-26 22:51:58  EePEg27-WCsk         python
13 TW90b3JzIGFuZCBTZW5zb3Jz                 Motors and Sensors                         928b  22622 2020-10-29 19:32:08  RHyxoO9ZeutF         scratch
17 hub/program_template.py                  hub/program_template.py                    306b  31408 2020-10-29 13:19:26
19 cHl0aG9uX2NvbG9yc2Vuc29y                 python_colorsensor                        1447b  23262 2020-07-27 18:57:02  gQk2tmN-Bts4         python
                                                            28476/31744kb Free
```
The program in slot 17 has been uploaded with your tool. The project-id is empty there.

The output is a bit wide, and probably not all fields are usefull.
What do you think?
I might make a pull request if you like.

**Comment by BertLindeman** [comment]
Additional note, upload using `./spikejsonrpcapispike.py` adds the project-id and type.


```
./spikejsonrpcapispike.py upload hub/program_template.py 18
```

```
 ./spikejsonrpc_bert.py ls
 # Name                                     Decoded Name                               Size     Id Last Modified        Project_id           Type
 0 YXZhaWxhYmxlbW9kdWxlcw==                 availablemodules                           740b  41475 2020-10-28 21:54:08  EePEg27-WCsk         python
 1 dHJ5X21vZHVsZXM=                         try_modules                                357b  51754 2020-09-18 10:39:11  JZGKRQp5EUqj         python
 3 ZGlyZWN0b3J5X2xpc3Q=                     directory_list                            1725b  11624 2020-07-27 19:54:17  AIKWkHYSy_Z9         python
 9 UHJpbWVDdWJlci12MXAx                     PrimeCuber-v1p1                           1662b  31645 2020-07-26 18:02:38  3z6tt5wxuY6u         python
10 YXZhaWxhYmxlbW9kdWxlcw==                 availablemodules                           494b  41154 2020-07-26 22:51:58  EePEg27-WCsk         python
13 TW90b3JzIGFuZCBTZW5zb3Jz                 Motors and Sensors                         928b  22622 2020-10-29 19:32:08  RHyxoO9ZeutF         scratch
17 hub/program_template.py                  hub/program_template.py                    306b  31408 2020-10-29 13:19:26
18 hub/program_template.py                  hub/program_template.py                    519b  57859 2020-10-29 20:04:00  50uN1ZaRpHj2         python
19 cHl0aG9uX2NvbG9yc2Vuc29y                 python_colorsensor                        1447b  23262 2020-07-27 18:57:02  gQk2tmN-Bts4         python
                                                            28472/31744kb Free
```

**Comment by sanjayseshan** [comment]
I will take a look when I get a chance. In my recent tests at least the upload function worked correctly only in the `spikejsonrpcapispike.py`.  The spikejsonrpcapispike.py is needed to work on newer firmware releases (since the official spike api release). The old (non-apispike version) does not create the proper project_id field on the newest firmware. spikejsonrpcapispike.py should also work on the new MINDSTORMS.

If you are able to submit a pull request, that would be great. 

Note that if you use the vscode wrapper for these tools, you should take a look at https://github.com/sanjayseshan/spikeprime-vscode/wiki/SPIKE-API (the basic instructions download the tools for the older firmware and have not been updated yet).

**Comment by BertLindeman** [comment]
To keep the issue a bit clean, I will create a separate issue for the list command re-format.
And try to make a PR (I am a bit rusty on git).
I am doing git straight on linux mint, so no vscode interference .

**Comment by ingoha** [comment]
Is this issue resolved by the patch by @smr99?
#https://github.com/smr99/spikeprime-tools/commit/0aa6804ad7324eb17fa1e83797950e91f0ee28c8

**Comment by smr99** [comment]
> Is this issue resolved by the patch by @smr99?
> #[smr99@0aa6804](https://github.com/smr99/spikeprime-tools/commit/0aa6804ad7324eb17fa1e83797950e91f0ee28c8)

I believe it does -- at least for my "Robot Inventor" hub.  I wasn't sure whether the change was "Robot Inventor" specific so I didn't make a PR.

**Comment by sanjayseshan** [comment]
> > Is this issue resolved by the patch by @smr99?
> > #[smr99@0aa6804](https://github.com/smr99/spikeprime-tools/commit/0aa6804ad7324eb17fa1e83797950e91f0ee28c8)
> 
> I believe it does -- at least for my "Robot Inventor" hub. I wasn't sure whether the change was "Robot Inventor" specific so I didn't make a PR.

I have not tested it on SPIKE Prime, but this fix should (most likely) work for both. It should solve this problem.

**Comment by ingoha** [comment]
Works for me as well (Robot Inventor hub, Firmware version: 1.0.6.34; Runtime version: 2.1.4.13). Should I create a pull request?

**Comment by BertLindeman** [comment]
@smr99 Have editted my spikejsonrpc like the changes in pull request #8 and it works!

Did it on my SpikeHub at ```Firmware version: 1.0.6.34; Runtime version: 2.1.4.13```

And on my InventorHub at ```Firmware version: 1.0.6.34; Runtime version: 2.1.4.13```

**Comment by sanjayseshan** [comment]
Awesome! Closing now since it works.
