### ISSUE TITLE
readme describes spikejsonrpc.py but you advise to use spikejsonrpcapispike.py

### ISSUE THREAD

**Issue by BertLindeman** [sanjayseshan/spikeprime-tools#2]
Title describes it all.

**Comment by sanjayseshan** [comment]
Yep. I will fix that. `spikejsonrpc.py` no longer works on the newest firmware unfortunately as programs need to be labelled slightly differently.

**Comment by BertLindeman** [comment]
Great,
Thank you.

[EDIT] typo
